FROM node:18-alpine as compiler

WORKDIR /app

COPY package.json package-lock.json tsconfig.json ./

RUN npm ci

COPY . ./

RUN npm run build

FROM node:18-alpine as remover

WORKDIR /app

COPY --from=compiler /app/LICENSE ./

COPY --from=compiler /app/package.json /app/package-lock.json ./

COPY --from=compiler /app/build ./build

RUN npm ci --only=prod

FROM gcr.io/distroless/nodejs:18

WORKDIR /app

COPY --from=remover /app .

USER 1000

CMD ["build/main.js"]
